### ISSUE TITLE
型定義の見直し

### ISSUE THREAD

**Issue by hiro08gh** [microcmsio/microcms-js-sdk#4]
型定義の見直しを行っています。

型定義に関して、ご意見やバグフィックス等ありましたらコメント頂けると助かります。

**Comment by aiji42** [comment]
非常にシンプルなSDKで、実装も追いやすく助かっています。  
開発ありがとうございます。

こちらのIssueに該当するかわかりませんが、  
`client.get`で`contentId`を指定していなければ、返り値が自動的に `{ contents: Array<T> }`となるようにしていただけると、助かります。

```ts
  // getOne
  client.get<Post>({
    endpoint: 'posts',
    contentId: params.id
  })

  // getList
  client.get<{ contents: Array<Post> }>({ // { contents Array<> } のところを省略したい
    endpoint: 'posts'
  })
```

時間が確保できれば、PR出させていただくかもしれません。

**Comment by hiro08gh** [comment]
コメントありがとうございます！
現在型定義を見直してる状況なので、ご意見頂き非常に助かります！

ご意見を参考に検討させていただきます。少しだけお時間を頂けたら嬉しいです。

**Comment by dai65527** [comment]
以下のようにclientをwrapしたい場合に、型定義があると嬉しいなあと思いました。（以下のMicroCMSClient型のような）

```ts
export default class APIClient {
  private client: MicroCMSClient;

  constructor() {
    this.client = createClient({
      serviceDomain: APIConfig.microCMSServiceDomain,
      apiKey: APIConfig.microCMSApiKey,
    });
  }
  ...
}
```

**Comment by amotarao** [comment]
`src/types.ts` に定義されている interface を直接呼び出せるようになると嬉しいです。

現状 package.json の types は `./dist/cjs/index.d.ts` を指していますが、
`dist/cjs/types.d.ts` の内容がそのまま export されるようになっていないようです。

**Comment by hiro08gh** [comment]
コメントありがとうございます！

types.tsのinterfaceを呼び出せるように修正致します。もし、不具合等あればPR等頂けたら嬉しいです！

**Comment by dc7290** [comment]
@hiro08gh 
公式の型があることで、いつも助かっています。
ありがとうございます！

本題ですが、
https://github.com/microcmsio/microcms-js-sdk/blob/main/src/types.ts#L39
こちらの型定義の`publishedAt `と`revisedAt `は下書きの段階では`undefined`のため、
```ts
publishedAt?: string
revisedAt?: string
```
とするのは、どうでしょうか？

この提案は破壊的変更に入ると思うので、
慎重に考える必要がありますが、ぜひ検討をお願いいたします。

また、この提案を採用していただける場合に、
お時間が厳しいようでしたら、こちらでPRを作成いたしますので、お伝えください。
