### ISSUE TITLE
`get()` 実行時、 `contentId` を指定しなかった場合型と実際の値が乖離してしまう

### ISSUE THREAD

**Issue by SawadaReverse** [microcmsio/microcms-js-sdk#48]
https://github.com/microcmsio/microcms-js-sdk/issues/4#issuecomment-846720062 で指摘されている内容と同様です。
以下の条件でジェネリクスに記述した型と実際に返される値の型が乖離してしまいます。

```ts
type article = {
  body: string
}
const endpoint = 'this-is-endpoint'
const queries: MicroCMSQueries = {
  filters: 'body[equals]hello'
}

await microCMS.get<article>({endpoint, queries}) // -> 定義上は article で返るはずだけど中身は MicroCMSListContent<article>

await microCMS.get<article>({endpoint, queries, contentId: 'article-id'}) // -> 定義通り article が返ってくる
```

**Comment by dc7290** [comment]
Issueの発行ありがとうございます！

結論からお伝えしますと、getListやgetObjectなどを使用いただけると幸いです。

microCMSのもてるデータ構造上、getのみだと適切な型定義を提供することができません。
これは同じエンドポイントの指定の仕方でリスト形式とオブジェクト形式のどちらも取得でき、
それがソースコードからは判定できないからです。。。
そのためgetをご使用いただく場合は、microCMSから提供されるデフォルトの値に関する型定義を含め、
全てユーザーが定義していただく必要があります。

TypeScriptでの使用方法は以下をご覧ください！
https://github.com/microcmsio/microcms-js-sdk#typescript

**Comment by SawadaReverse** [comment]
コメントありがとうございます。
microCMSの仕様上 `get()` に適切な型を当てるのは難しいという旨、承知しました。
(私が個人で作っているプロジェクトではオブジェクト形式しか使っておらず、リスト形式のことを全く考えていませんでした。)

これの代用として [getObject()](https://github.com/microcmsio/microcms-js-sdk/blob/acc4263ba7bec8d98ce9af665863161beecae38d/src/createClient.ts#L155-L166) を使おうと思うのですが、こちらも同様の問題が発生しております。
([makeRequest()](https://github.com/microcmsio/microcms-js-sdk/blob/acc4263ba7bec8d98ce9af665863161beecae38d/src/createClient.ts#L155-L166) では `contentId` が指定されていない場合一覧取得になってしまうためではないかと考えています)
こちらも `getObject()` のコードを読む限りでは指定したオブジェクト単体が返ってくるように見受けられますが、 `get()` と同様にユーザが定義した型を使って上書きするべきでしょうか？

なお、これ以降は `get()` の話とは逸れてしまいますので、別途Issueを建てるべきであればご指示いただければ幸いです。

**Comment by himorishige** [comment]
@SawadaReverse 

こんにちは。
私の認識が誤っていたらすみません、、

APIのスキーマはリスト形式ではなくオブジェクト形式を利用していますでしょうか？
https://document.microcms.io/manual/create-api

`getObject()`ですとオブジェクト形式のAPIを利用し、その際`contentId`での指定はできない型となっています。（データは常に1つのオブジェクトしかないため）
なお、`contentId`を指定してデータを取得したい場合はAPIのスキーマがリスト形式である前提ですが`getListDetail()`を使うことでリストの中から該当のidのものをオブジェクトとして取得可能です。

**Comment by SawadaReverse** [comment]
確認してきたところ、こちらの認識違いでした。
(オブジェクト形式はjsonをリストで返すもので、リスト形式は別のフォーマットでリストを返すものだと思っていました…)
大変お騒がせしました。解決したためcloseさせていただきます…。
