### ISSUE TITLE
microcms-js-sdkを使っている際に、HTTPステータスコードを取得できない

### ISSUE THREAD

**Issue by SYUN121098** [microcmsio/microcms-js-sdk#51]
axiosを使用した場合、error.response.statusでHTTPステータスコードを取得することが出来るのですが
microcms-js-sdkを使用している場合、ステータスコードのみを取得できないので、取得できるようにしてほしいです。

**Comment by dc7290** [comment]
フィードバックありがとうございます！

以下のPRに統合しますね！
https://github.com/microcmsio/microcms-js-sdk/issues/47
